
# Generated by Django 5.0.14 on 2026-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
