# Generated by Django 5.0.14 on 2026-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_uploadedfile_extracted_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("pdf", "PDF"),
                    ("docx", "DOCX"),
                    ("txt", "TXT"),
                    ("audio", "Audio"),
                ],
                max_length=20,
            ),
        ),
    ]
