# Generated by Django 5.0.14 on 2026-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_uploadedfile_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="drive_file_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="drive_view_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
