# Generated by Django 5.0.14 on 2026-09-03 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_uploadedfile_extracted_text"),
        ("search", "0002_searchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_json", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_embedding",
                        to="files.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
